theme: jekyll-theme-cayman
title: GrafanaAlarmPanel.documentation
description: OpenHistorian Device Status Alarm Panel Documentation
github:
  repository_name: openHistorianGrafanaAlarmPanel
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji